# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [55]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [56]:
print(np.__version__)
print(np.show_config)

1.21.6
<function show at 0x7f5dc389fc20>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [57]:
a=np.zeros(10,dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [58]:
print(a.size)
print(a.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [59]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [60]:
a = np.zeros(10,dtype=int)
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [61]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [62]:
b=a[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [63]:
a = np.arange(0,9)
b = a.reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [64]:
b = np.nonzero([1,2,0,0,4,0])
print(b)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [65]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [66]:
a = np.random.random((3,3,3))
print(a)

[[[0.07015421 0.87690352 0.83214098]
  [0.42319514 0.6319537  0.25179944]
  [0.38940915 0.50325416 0.21149285]]

 [[0.37091244 0.3033215  0.97091351]
  [0.96998645 0.35640134 0.63542358]
  [0.21973207 0.80221204 0.60574704]]

 [[0.99303063 0.17907216 0.25953099]
  [0.54156059 0.73650245 0.56222702]
  [0.52851412 0.56358008 0.32077785]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [67]:
a = np.random.random((10,10))
print("minimum = ", a.min())
print("maximum = ", a.max())

minimum =  0.0006771379549634915
maximum =  0.9921819067206382


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [68]:
a = np.random.random(30)
m = a.mean()
print(m)

0.5384495262340333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [69]:
a = np.array([[1,0,1], [1,0,1]])
print(a)
print("\n")
b = np.array([[1,1,1], [1,0,1], [1,1,1]])
print(b)
print("\n")
c=np.ones((5,5))
c[1:-1,1:-1]=0
print(c)

[[1 0 1]
 [1 0 1]]


[[1 1 1]
 [1 0 1]
 [1 1 1]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [70]:
x = np.ones(3)
y = np.pad(x, pad_width=1)
y

array([0., 1., 1., 1., 0.])

In [71]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.pad(x, pad_width=1)
y

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [72]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [73]:
a = np.diag([1,2,3,4],k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [74]:
a = np.zeros((8,8))
a[::2,1::2] = 1
a[1::2,::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [75]:
a = np.arange(336).reshape(6,7,8)
np.unravel_index(335,(6,7,8))

(5, 6, 7)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [76]:
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [77]:
a = np.random.random((5,5))
a_max = a.max()
a_min = a.min()
diff = a_max - a_min
a = (a-a_min)/(a_max-a_min)
a

array([[0.93164097, 0.17324483, 0.33496397, 0.43527628, 1.        ],
       [0.01928084, 0.2428045 , 0.65930591, 0.59714233, 0.28878157],
       [0.09007227, 0.65964796, 0.51406152, 0.61576935, 0.74543433],
       [0.26631842, 0.12575966, 0.31575311, 0.07772905, 0.82276585],
       [0.33869647, 0.        , 0.76979125, 0.54075846, 0.3140006 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [78]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [79]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
c = np.dot(a,b)
print(a,b,c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] [[0 1]
 [2 3]
 [4 5]] [[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [80]:
a = np.arange(20)
a[(3 < a) & (a <= 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15 16 17 18 19]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [81]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [83]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [84]:
a = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(a)), a))

[-5. -4.  6. -7. -5. -2. -1. -1.  4. -6.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [85]:
a = np.random.randint(1,10,10)
b = np.random.randint(1,10,10)
a,b,np.intersect1d(a,b)

(array([3, 3, 2, 1, 4, 4, 3, 6, 4, 2]),
 array([1, 5, 5, 9, 1, 5, 9, 1, 5, 9]),
 array([1]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [86]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)
_ = np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3) / 0

[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [87]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [88]:
today = np.datetime64("today",'D')
tomorrow = today + np.timedelta64(1,"D")
yesterday = today - np.timedelta64(1,"D")
today, yesterday, tomorrow

(numpy.datetime64('2022-08-16'),
 numpy.datetime64('2022-08-15'),
 numpy.datetime64('2022-08-17'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [89]:
d1 = np.arange('2016-07','2016-08', dtype="datetime64[D]")
d1

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [90]:
A = np.arange(1,4, dtype=float)
B = np.arange(1,4, dtype=float) * 2
C = np.arange(1,4, dtype=float) * 3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[ -1.5  -6.  -13.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [91]:
i = 70*np.random.randn(5)
j = np.trunc(i)
k = np.around(i)
l = np.floor(i)
m = np.ceil(i)
n = i.astype(int)
i,j,k,l,m,n

(array([ 18.18259246,  28.05182157,  22.91150522,  79.38103228,
        -57.16580208]),
 array([ 18.,  28.,  22.,  79., -57.]),
 array([ 18.,  28.,  23.,  79., -57.]),
 array([ 18.,  28.,  22.,  79., -58.]),
 array([ 19.,  29.,  23.,  80., -57.]),
 array([ 18,  28,  22,  79, -57]))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [92]:
a = np.ones((5,5)) + np.arange(5)
a

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [93]:
def generate():
    for x in range(10):
        yield x
a = np.fromiter(generate(),dtype=int,count=-1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [94]:
a = np.linspace(0,1,11,endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [95]:
x=np.random.random(10)
x.sort()
x

array([0.03820459, 0.15154222, 0.1664262 , 0.24980329, 0.2609671 ,
       0.34069282, 0.42161766, 0.63563998, 0.85011642, 0.89317899])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [96]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [97]:
a = np.arange(4)
b = np.arange(4)
np.array_equal(a,b)

True

43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [98]:
a=np.zeros(10)
print(a)
a[1]=10
print(a)
a.flags.writeable=False
a[1]=10

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [99]:
a = np.random.random((10,2))
print(a,"\n")
b,c = a[:,0], a[:,1]
d = np.sqrt(b**2+c**2)
e = np.arctan2(c,b)
print(d,"\n")
print(e,"\n")

[[0.60730215 0.54893201]
 [0.83530426 0.05700128]
 [0.24376184 0.8326446 ]
 [0.98867876 0.01567622]
 [0.83757456 0.48691628]
 [0.36867064 0.91655454]
 [0.5350303  0.47221532]
 [0.61173558 0.68303668]
 [0.89160443 0.55010432]
 [0.26194212 0.02294109]] 

[0.81862217 0.83724689 0.86759257 0.98880303 0.96882331 0.9879222
 0.71361385 0.9169294  1.04765129 0.2629448 ] 

[0.73495801 0.06813451 1.28599843 0.0158544  0.52658651 1.18836441
 0.7231157  0.84041105 0.55281313 0.08735788] 



#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [100]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.27211225, 0.46658228, 0.6566694 , 0.        , 0.09492079,
       0.55907642, 0.29136486, 0.7104656 , 0.49827322, 0.04179152])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [101]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [102]:
a = np.arange(8)
b = a + 0.5
c = 1.0 / np.subtract.outer(a, b)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [103]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [104]:
np.set_printoptions(threshold=float("inf"))
a = np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [105]:
a = np.arange(5)
b = np.random.uniform(0,5)
index = (np.abs(a-b)).argmin()
index,print(a[index])

2


(2, None)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [106]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [107]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.44155025 0.43264571 0.70533275 0.76460222 0.80640746
  0.78884379 0.17608748 0.5197261  0.91029085]
 [0.44155025 0.         0.75989176 0.94153585 1.0101818  0.60651114
  0.8818139  0.53654721 0.50181609 1.13464694]
 [0.43264571 0.75989176 0.         0.2983815  0.34630164 0.79470064
  0.49354078 0.25893964 0.47099141 0.49414279]
 [0.70533275 0.94153585 0.2983815  0.         0.06896194 0.76370222
  0.28945141 0.53025183 0.50677587 0.20544359]
 [0.76460222 1.0101818  0.34630164 0.06896194 0.         0.82158982
  0.32600554 0.58874307 0.57360519 0.14787877]
 [0.80640746 0.60651114 0.79470064 0.76370222 0.82158982 0.
  0.53058469 0.75085769 0.32947193 0.87914368]
 [0.78884379 0.8818139  0.49354078 0.28945141 0.32600554 0.53058469
  0.         0.63650924 0.38185151 0.35116927]
 [0.17608748 0.53654721 0.25893964 0.53025183 0.58874307 0.75085769
  0.63650924 0.         0.43163001 0.73481817]
 [0.5197261  0.50181609 0.47099141 0.50677587 0.57360519 0.32947193
  0.38185151 0.43163

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [108]:
x = np.arange(1,10,dtype=float)
y = x.astype(int)
print(x)
print(y)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [109]:
from numpy.lib.npyio import genfromtxt
from io import StringIO as st
s = st("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
x = np.genfromtxt(s,delimiter=",",dtype=int)
x

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [110]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [111]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [112]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [113]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
y = x - x.mean(axis=1).reshape(-1, 1)
print(y)

[[-0.33377286  0.24953121 -0.27682853 -0.36021699  0.15049822  0.07835204
  -0.01936453  0.08658327  0.31388692  0.11133126]
 [-0.04998181  0.59188492 -0.26068853  0.08096917 -0.0941965  -0.20346861
   0.59117695 -0.25037456 -0.36221946 -0.04310156]
 [ 0.36993771 -0.53777332 -0.36656443 -0.21001632  0.20826137  0.39616667
  -0.18800773  0.20249441 -0.24382666  0.3693283 ]
 [ 0.09365346 -0.02306407  0.00421272 -0.31602975 -0.17596889 -0.22903859
  -0.01305011  0.48757114  0.00812335  0.16359074]
 [-0.06569171  0.22861407 -0.00440226  0.36656188  0.30748154 -0.488827
   0.07241989 -0.23468304 -0.23779145  0.05631807]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [114]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[7 5 0]
 [5 2 7]
 [1 8 3]]
[[5 2 7]
 [7 5 0]
 [1 8 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [115]:
a = np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [116]:
Z = np.random.uniform(0,1,10)
z = 0.5
x = np.abs(Z - z).argmin()
m = Z.flat[x]
print(x, m)

8 0.47557507724123405


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [117]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it: 
  z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [118]:
class namedarray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

a = namedarray(np.arange(10), "range_10")
print(a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [119]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)
np.add.at(a, b, 1)
print(a)

[3. 5. 3. 2. 3. 5. 1. 1. 3. 4.]
[5. 9. 5. 3. 5. 9. 1. 1. 5. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [120]:
a = [1,2,3,4,5,6]
b = [1,5,7,9,3,5]
c = np.bincount(b,a)
print(c)

[0. 1. 0. 5. 0. 8. 0. 3. 0. 4.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [121]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [122]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[79 61 50 67]
 [54 46 50 55]
 [64 60 60 65]]
[[79 61 50 67]
 [54 46 50 55]
 [64 60 60 65]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [123]:
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
print(pd.Series(D).groupby(S).mean())

[0.62120384 0.63302142 0.55764449 0.51121173 0.38750487 0.62069898
 0.49650224 0.72061014 0.57520601 0.5314946 ]
0    0.621204
1    0.633021
2    0.557644
3    0.511212
4    0.387505
5    0.620699
6    0.496502
7    0.720610
8    0.575206
9    0.531495
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [124]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

A,B,np.diag(np.dot(A, B))

(array([[0.02978621, 0.20490407, 0.67548423, 0.46403022, 0.88800976],
        [0.13907981, 0.51925921, 0.60020524, 0.68602922, 0.97991439],
        [0.11778105, 0.16329735, 0.60451898, 0.05817543, 0.23363626],
        [0.97894359, 0.88964164, 0.31113327, 0.48710216, 0.38898335],
        [0.81514255, 0.54182722, 0.09299959, 0.96325315, 0.23438825]]),
 array([[0.47554164, 0.91849595, 0.26027986, 0.97487763, 0.84922289],
        [0.50641367, 0.69087628, 0.9356666 , 0.05604568, 0.60659046],
        [0.20972029, 0.8925705 , 0.2058701 , 0.48602332, 0.14815689],
        [0.24579755, 0.15702188, 0.56461643, 0.33038986, 0.05391733],
        [0.16649602, 0.02486985, 0.10916987, 0.13449486, 0.23363603]]),
 array([0.52150114, 1.15430553, 0.36625314, 1.36867869, 1.14138104]))

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [125]:
a = np.array([1,2,3,4,5])
b = 3
c = np.zeros(len(a) + (len(a)-1)*(b))
c[::b+1] = a
print(c)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [126]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [127]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [128]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 6, 61) ( 6, 66) ( 7, 55) ( 7, 82) ( 9, 33) ( 9, 46) (21, 32) (21, 50)
 (32, 50) (33, 46) (37, 55) (37, 94) (48, 83) (48, 94) (49, 58) (49, 91)
 (51, 64) (51, 69) (53, 57) (53, 69) (55, 82) (55, 94) (57, 69) (58, 91)
 (61, 66) (64, 69) (71, 83) (71, 92) (83, 92) (83, 94)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [129]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)), c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [130]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [131]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [132]:
Z = np.random.uniform(-1.0,1.0,10)
print(Z)
np.negative(Z, out=Z)
print(Z)

[-0.8149863   0.01815225  0.89144178 -0.54883622  0.31184302  0.89675234
 -0.22037809 -0.35546613  0.99472391 -0.02432865]
[ 0.8149863  -0.01815225 -0.89144178  0.54883622 -0.31184302 -0.89675234
  0.22037809  0.35546613 -0.99472391  0.02432865]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [133]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.36561033  6.06476279  2.76520437  3.44101126  5.25565738 10.8898481
 11.97292989  5.63239812  9.82421861  7.2524284 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [134]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.58288141  8.03708639 10.23438118  8.06559521 11.90627045  6.82808702
   1.13507691 12.05861199  8.50543558  7.3830856 ]
 [ 1.70013381  9.96748495  5.22620344  3.74808511  0.6150131  11.51644362
   4.41271882  6.98537828  2.57922964  5.1882514 ]
 [ 6.27150334  3.99136651 11.4624757   1.25982128  5.02854689  4.53396059
   8.08476657  4.98840395  1.6022836  10.28159182]
 [ 9.54867288  2.47057761 12.44361717  1.75710004  1.96366112  3.87355427
  11.38359844  1.67553086  1.48009887 12.00346345]
 [ 1.95364495  3.81735331  2.07609989  2.16864256  6.43909749  6.07863342
   0.47728561 11.40592435  3.20684846  3.48788072]
 [ 1.19565013  2.02353565  4.05073379  5.02010523  9.07633407  0.30454187
   0.88231689 11.6502744   5.76008402  1.94297976]
 [ 7.18376743  3.39451769  0.91668463  9.72580026 13.91585096  0.02537142
   5.06400035 17.47387913 10.64974807  2.34737558]
 [ 3.68479098 11.53040984 16.72706937  7.2740722  10.87273476 11.74527117
   5.1145408   8.63773082  7.37844238 14.07376557]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [135]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 1 5 4 0 0 0 2 4 8]
 [3 5 1 4 7 3 6 3 4 5]
 [6 9 3 2 7 6 9 4 2 4]
 [3 3 5 3 3 4 3 6 7 1]
 [5 8 9 3 2 5 9 6 9 9]
 [1 0 5 1 3 5 9 8 4 4]
 [7 5 1 0 9 1 6 0 3 5]
 [2 9 4 3 5 9 6 4 2 8]
 [5 1 2 4 3 1 8 2 2 8]
 [0 8 2 5 6 9 6 0 5 9]]
[[0 0 0 0 0]
 [0 9 1 5 4]
 [0 3 5 1 4]
 [0 6 9 3 2]
 [0 3 3 5 3]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [136]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [137]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [138]:
x = np.random.randint(1,5,5)
print(x) 
print(np.bincount(x)) 
print(np.bincount(x).argmax())

[2 3 4 3 4]
[0 0 1 2 2]
3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [139]:
z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (z.shape[0]-3)
j = 1 + (z.shape[1]-3)
c = stride_tricks.as_strided(z, shape=(i, j, n, n), strides=z.strides + z.strides)
print(c)

[[[[4 0 3]
   [3 0 4]
   [1 1 2]]

  [[0 3 3]
   [0 4 0]
   [1 2 2]]

  [[3 3 2]
   [4 0 2]
   [2 2 3]]

  [[3 2 1]
   [0 2 1]
   [2 3 0]]

  [[2 1 2]
   [2 1 0]
   [3 0 4]]

  [[1 2 3]
   [1 0 0]
   [0 4 1]]

  [[2 3 0]
   [0 0 4]
   [4 1 3]]

  [[3 0 1]
   [0 4 0]
   [1 3 1]]]


 [[[3 0 4]
   [1 1 2]
   [3 0 4]]

  [[0 4 0]
   [1 2 2]
   [0 4 4]]

  [[4 0 2]
   [2 2 3]
   [4 4 1]]

  [[0 2 1]
   [2 3 0]
   [4 1 1]]

  [[2 1 0]
   [3 0 4]
   [1 1 0]]

  [[1 0 0]
   [0 4 1]
   [1 0 0]]

  [[0 0 4]
   [4 1 3]
   [0 0 1]]

  [[0 4 0]
   [1 3 1]
   [0 1 2]]]


 [[[1 1 2]
   [3 0 4]
   [0 3 2]]

  [[1 2 2]
   [0 4 4]
   [3 2 0]]

  [[2 2 3]
   [4 4 1]
   [2 0 2]]

  [[2 3 0]
   [4 1 1]
   [0 2 3]]

  [[3 0 4]
   [1 1 0]
   [2 3 2]]

  [[0 4 1]
   [1 0 0]
   [3 2 2]]

  [[4 1 3]
   [0 0 1]
   [2 2 0]]

  [[1 3 1]
   [0 1 2]
   [2 0 3]]]


 [[[3 0 4]
   [0 3 2]
   [3 0 1]]

  [[0 4 4]
   [3 2 0]
   [0 1 1]]

  [[4 4 1]
   [2 0 2]
   [1 1 4]]

  [[4 1 1]
   [0 2 3]
   [1 4 1]]

  [[1 1 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [140]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  5 12  3 13]
 [ 5  2 10 12 10]
 [12 10  2 42  2]
 [ 3 12 42  7  8]
 [13 10  2  8  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [141]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [142]:
a = np.ones((16,16))
b = 4
c = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], b), axis=0),
                                       np.arange(0, a.shape[1], b), axis=1)
print(c)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [143]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
  0 0 0 0 0 1 1 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0
  0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0
  0 0 0 1 1 0 1 1 1 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0
  0 0 0 1 1 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [144]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9996 9998 9999 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [145]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [146]:
a = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
r = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(r)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [148]:
a= np.random.randint(0,5,(8,3))
b= np.random.randint(0,5,(2,2))

c = (a[..., np.newaxis, np.newaxis] == b)
rows = np.where(c.any((3,1)).all(1))[0]
print(rows)

[0 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [149]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 3 1]
 [3 3 4]
 [1 4 2]
 [1 4 4]
 [3 2 2]
 [1 1 0]
 [0 3 2]
 [2 2 4]
 [4 4 1]
 [2 2 3]]
[[4 3 1]
 [3 3 4]
 [1 4 2]
 [1 4 4]
 [3 2 2]
 [1 1 0]
 [0 3 2]
 [2 2 4]
 [4 4 1]
 [2 2 3]]
[[4 3 1]
 [3 3 4]
 [1 4 2]
 [1 4 4]
 [3 2 2]
 [1 1 0]
 [0 3 2]
 [2 2 4]
 [4 4 1]
 [2 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [150]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [151]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]
[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [152]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)    

array([[0.70965294, 0.40064317, 0.37777395, 0.24659755, 0.69958935,
        0.62564139, 0.53175678, 0.85760143, 0.83870642, 0.23866083],
       [0.07886196, 0.04452248, 0.04198108, 0.02740377, 0.07774362,
        0.06952597, 0.0590928 , 0.09530311, 0.09320335, 0.02652178],
       [0.6260268 , 0.35343102, 0.33325673, 0.21753827, 0.61714912,
        0.55191525, 0.46909408, 0.75654091, 0.7398725 , 0.21053682],
       [0.64632407, 0.36489009, 0.3440617 , 0.22459138, 0.63715855,
        0.56980965, 0.48430322, 0.78106975, 0.76386092, 0.21736293],
       [0.48960486, 0.27641236, 0.26063439, 0.17013296, 0.48266177,
        0.43164348, 0.36687046, 0.59167771, 0.57864163, 0.16465725],
       [0.30452807, 0.17192502, 0.16211132, 0.10582057, 0.30020956,
        0.26847683, 0.22818882, 0.36801611, 0.35990783, 0.10241474],
       [0.30326419, 0.17121148, 0.16143851, 0.10538138, 0.2989636 ,
        0.26736257, 0.22724177, 0.36648873, 0.35841411, 0.10198969],
       [0.04225047, 0.02385302, 0.0224914

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [153]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [154]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [155]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.10376993  0.30156258]
